name: Run all tests

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        pyversion:
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - uses: actions/checkout@v4

      - name: Install Hatch
        uses: pypa/hatch@install

      - name: Test with hatch
        run: |
          hatch run +py=${{ matrix.pyversion }} test:run
